### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Levi-Armstrong** [tesseract-robotics/boost_plugin_loader#1]
- [x] Discuss method names
- [x] Discuss the custom exception class

Notes: This a port of the plugin loader class from Tesseract with most of @marip8 restructure. His restructure did not include some of the utility function so most of those were put into utils.h and utils.cpp. Also did not port the unit tests because Tesseract unit tests already provided 100% unit test coverage of all utility add plugin loader class.

**Comment by marip8** [comment]
- [x] Add changes/bug fixes from [this PR](https://github.com/marip8/plugin_loader/pull/3)

Per our conversation today:
>  Discuss method names

Decided to rename `getAllAvailablePlugins` to `getAvailablePlugins` to be consistent with existing functions in `tesseract` version

>  Discuss the custom exception class

Reintroduce the plugin loader custom exception so exceptions throw by this class can be specifically caught

**Comment by Levi-Armstrong** [comment]
It looks like at some point I updated Tesseract to use ":" so we are good there, but I fixed the search issue.

**Comment by marip8** [comment]
We should add CPack to this package as well

**Comment by marip8** [comment]
> We should add CPack to this package as well

See [this PR](https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/pull/62) that adds a macro to the boilerplate tools
